version: 2.1
commands:
  checkout_and_restore_cache:
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}

executors:
  node:
    docker:
      - image: circleci/node:12.22-browsers-legacy

jobs:
  install:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  build:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: |
          npm build

  test:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: 
          name: Run unit test
          command: |
            npm test

workflows:
  version: 2
  integration:
    jobs:
      - install
      - build:
          requires: 
              - install
      - test:
          requires: 
              - install