version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.22-browsers-legacy
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: npm install
      - run: |
          npm build

  test:
    docker:
      - image: circleci/node:12.22-browsers-legacy
    steps:
      - checkout
      - run: 
          name: Run unit test
          command: |
            npm test

workflows:
  version: 2
  integration:
    jobs:
      - build
      - test